apiVersion: v1
kind: Service
metadata:  
  name: clusteripsrv
spec:
    type: ClusterIP
    selector:
           app: deployapplap
    ports:
        - port: 80
          targetPort: 80
          name: http
          protocol: TCP
          
