apiVersion: v1
kind: Pod
metadata: 
      name: new-app-lb
spec:
    containers: 
        - name: nginx 
          image: nginx:latest
          resources: 
            requests:
              cpu: "100m"
              memory: "128Mi" 
          ports: 
              - containerPort: 81
                name: http
                protocol: TCP
        - name: tomcat 
          image: tomcat:latest
          resources: 
            requests:
              cpu: "100m"
              memory: "128Mi" 
          ports: 
              - containerPort: 8080
                name: java
                protocol: TCP