apiVersion: v1
kind: Pod
metadata: 
      name: new-app
      namespace: edtech
spec:
    containers: 
        - name: nginx 
          image: nginx:latest
          resources: 
            requests:
              cpu: "500m"
              memory: "128Mi" 
          ports: 
              - containerPort: 80
                name: http
                protocol: TCP
        - name: tomcat 
          image: tomcat:latest
          resources: 
            requests:
              cpu: "500m"
              memory: "128Mi" 
          ports: 
              - containerPort: 8080
                name: java
                protocol: TCP

---
apiVersion: v1
kind:  Service
metadata: 
      name: nodeport
      namespace: edtech
spec:
    type: NodePort  
    selector: 
      app: new-app
    ports:
        - port: 80
          targetPort: 80
          name: nginx
          protocol: TCP
        - port: 8080
          targetPort: 8080
          name: tomcat
          protocol: TCP