apiVersion: v1
kind: Pod
metadata: 
  name: nginxpodci
  labels:
    app: nginxpodci
spec:
  containers:
    - name: mynginxcontainer
      image: nginx:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
      app: nginxpodci
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

