apiVersion: apps/v1
kind: Deployment
metadata: 
        name: studentapp
        labels:
          app: studentapp
spec:
    replicas: 4
    strategy: 
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
    template:
        metadata:
            name: studentapp
            labels:
                  app: studentapp
        spec:
            containers:
              - name: dep-container
                image: nginx
                ports:
                - containerPort: 80
                  protocol: TCP
    selector:
        matchLabels:
            app: studentapp




