apiVersion: v1
kind: Pod
metadata:
  name: nginxpodlb
  labels:
    app: nginxpodlb
spec:
  containers:
    - name: mynginxcontainer1
      image: nginx:latest
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-servicelb
  labels: 
    app: nginxpodlb
spec:
  type: LoadBalancer
  selector:
    app: nginxpodlb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80    