apiVersion: v1
kind: Pod
metadata: 
  name: nginxpodnp
  labels:
    app: nginxpodnp
spec:
  containers:
    - name: mynginxcontainer1
      image: nginx:latest
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-servicenp
  labels: 
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginxpodnp
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80

