apiVersion: v1
kind: pod
metadata:
  name: mypod-ns
  namespace: my-ns
  labels:
    app: myapp
spec:
  containers:
  - name: mynscontainer
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: my-ns

spec:
  selector:
    app: myapp
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-ns
  labels:
    app: myapp