apiVersion: v1
kind: PersistentVolumeClaim
metadata:
      name: pvc-volume
spec:
      storageClassName: standard
      volumeMode: Filesystem
      accessModes:
      - ReadWriteOnce
      resources:
          requests: 
            storage: 3Gi