apiVersion: apps/v1
kind: StatefulSet
metadata:
        name: ss
        labels:
            app: ss
spec:
      replicas: 3 #no of replica's you want to create on the basis of template
      template:
        metadata: #like a tag
             name: ss
             labels: 
               app: ss
        spec:
            containers: 
              - name: sspod-con
                image: mysql:latest
                resources:
                    requests:
                      cpu: "50m"
                      memory: "90Mi"

                ports:
                  - name: dbport 
                    containerPort: 3306
                    protocol: TCP
      selector:
        matchLabels:
          app: ss
