apiVersion: apps/v1
kind:  Deployment
metadata:  
   name: testdeployment
   labels: 
      app: testapp
spec:
  replicas: 2
  selector: 
      matchLabels: 
        app: testapp
  strategy: 
        type: RollingUpdate
  template:  
    metadata:
      name: testpod
      labels:
        app: testapp
    spec:
        containers:
          - image: anupdudhe/frontendrds
            name: nginx
            ports:
              -   containerPort: 80
                  protocol: TCP
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testdeployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
