apiVersion: v1
kind: Service
metadata:  
  name: clusteripsrvmob
spec:
    type: ClusterIP
    selector:
           app: deployappmob
    ports:
        - port: 8080
          targetPort: 8080
          name: http
          protocol: TCP
          
