apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: testdeployment
  labels: 
    app: newapp
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: newapp
  strategy:
   type: RollingUpdate
   rollingUpdate: 
    maxSurge: 2
    maxUnavailable: 0
  template:
    metadata: 
      labels: 
        app: newapp
    spec:
     containers:
        - name: mynginxapp
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
        
