
apiVersion: v1 
kind: Pod
metadata:
     name: first-pod
     namespace: dev
     labels:
      app: nginx
spec: 
  containers:
    - name: nginx 
      image: nginx:latest 
      ports: 
       - containerPort: 80
         protocol: TCP
    - name: tomcat
      image: tomcat:latest
      ports:
       - containerPort: 8080
         protocol: TCP
---
apiVersion: v1
kind: Service 
metadata:
 name: service1
 namespace: dev
spec:
  selector: 
    app: nginx 
  type: NodePort
  ports: 
    - port: 80 
      protocol: TCP
      targetPort: 80
      name: nginx
    - port: 8080 
      protocol: TCP
      targetPort: 8080
      name: tomcat

  #kubectl exec -it <pod_name> -c <container_name> -- <command>
    