apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:  
      myapp1: app3
    #app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      name: nginx
      port: 80
      targetPort: 80
    - protocol: TCP
      name: tomcat
      port: 8080
      targetPort: 8080