apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
      name: pvcvol
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi  
